"""
cookie_refresher.py — Playwright-based YouTube cookie extraction.

Launches a headless Chromium browser, visits YouTube, and exports the
cookies yt-dlp needs to bypass bot detection. No Google login required —
YouTube sets essential anti-bot cookies (CONSENT, VISITOR_INFO1_LIVE, etc.)
just from a normal page visit.

Usage:
    from cookie_refresher import refresh_cookies
    success = refresh_cookies()          # blocking, ~10-15s
    success = await arefresh_cookies()   # async variant
"""

import os
import time
import threading
from pathlib import Path
from datetime import datetime

_COOKIES_PATH = Path("cookies.txt")
_LOCK = threading.Lock()

# Minimum seconds between refresh attempts (avoid hammering YouTube)
_MIN_REFRESH_INTERVAL = 300  # 5 minutes
_last_refresh_attempt: float = 0.0


def _to_netscape(cookies: list[dict], domain: str = ".youtube.com") -> str:
    """Convert Playwright cookie dicts to Netscape HTTP Cookie File format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by cookie_refresher.py (Playwright)",
        f"# Refreshed: {datetime.utcnow().isoformat()}Z",
        "",
    ]
    for c in cookies:
        # Only keep YouTube / Google cookies relevant to yt-dlp
        cookie_domain = c.get("domain", "")
        if not any(d in cookie_domain for d in (".youtube.com", ".google.com", "youtube.com", "google.com")):
            continue

        http_only = "TRUE" if c.get("httpOnly", False) else "FALSE"
        # Netscape format: domain  include_subdomains  path  secure  expires  name  value
        include_sub = "TRUE" if cookie_domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expires", 0)))
        path = c.get("path", "/")
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{cookie_domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    return "\n".join(lines) + "\n"


def _is_rate_limited() -> bool:
    """Prevent refresh spam — enforce minimum interval between attempts."""
    global _last_refresh_attempt
    return (time.time() - _last_refresh_attempt) < _MIN_REFRESH_INTERVAL


def refresh_cookies(timeout: int = 60) -> bool:
    """
    Launch headless Chromium, visit YouTube, and export fresh cookies.
    Thread-safe. Returns True on success, False on failure.

    This does NOT require a Google login — YouTube sets anti-bot cookies
    (CONSENT, VISITOR_INFO1_LIVE, YSC, PREF, GPS) on any normal visit.
    These cookies are what yt-dlp needs to avoid "Sign in to confirm you're
    not a bot" blocks.
    """
    global _last_refresh_attempt

    if _is_rate_limited():
        elapsed = int(time.time() - _last_refresh_attempt)
        print(f"[cookie_refresher] rate limited — last attempt {elapsed}s ago (min {_MIN_REFRESH_INTERVAL}s)")
        return False

    if not _LOCK.acquire(blocking=False):
        print("[cookie_refresher] another refresh already in progress — skipping")
        return False

    try:
        _last_refresh_attempt = time.time()
        print("[cookie_refresher] starting Playwright cookie extraction...")

        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                ],
            )

            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/131.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1920, "height": 1080},
                locale="en-US",
                timezone_id="America/New_York",
            )

            # Remove webdriver indicator
            context.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
                // Overwrite the 'plugins' property to use a custom getter.
                Object.defineProperty(navigator, 'plugins', {
                    get: () => [1, 2, 3, 4, 5],
                });
                // Overwrite the 'languages' property to use a custom getter.
                Object.defineProperty(navigator, 'languages', {
                    get: () => ['en-US', 'en'],
                });
            """)

            page = context.new_page()
            page.set_default_timeout(timeout * 1000)

            # Step 1: Visit YouTube homepage — this sets the initial cookies
            print("[cookie_refresher] visiting youtube.com...")
            page.goto("https://www.youtube.com", wait_until="domcontentloaded")

            # Step 2: Handle the consent dialog if it appears (GDPR regions)
            try:
                # Look for "Accept all" or "Reject all" consent buttons
                consent_btn = page.locator(
                    'button:has-text("Accept all"), '
                    'button:has-text("Accept All"), '
                    'button:has-text("Reject all"), '
                    'button:has-text("I agree")'
                ).first
                if consent_btn.is_visible(timeout=5000):
                    consent_btn.click()
                    print("[cookie_refresher] dismissed consent dialog")
                    page.wait_for_timeout(2000)
            except Exception:
                pass  # No consent dialog — fine

            # Step 3: Wait for cookies to settle — YouTube sets them async
            page.wait_for_timeout(3000)

            # Step 4: Do a test search to trigger additional cookie grants
            try:
                print("[cookie_refresher] performing test search...")
                page.goto(
                    "https://www.youtube.com/results?search_query=music",
                    wait_until="domcontentloaded",
                )
                page.wait_for_timeout(3000)
            except Exception as e:
                print(f"[cookie_refresher] test search skipped: {e}")

            # Step 5: Extract all cookies
            cookies = context.cookies()
            browser.close()

        if not cookies:
            print("[cookie_refresher] ✗ no cookies extracted")
            return False

        # Filter to YouTube/Google cookies
        yt_cookies = [
            c for c in cookies
            if any(d in c.get("domain", "") for d in (".youtube.com", ".google.com", "youtube.com", "google.com"))
        ]

        if not yt_cookies:
            print("[cookie_refresher] ✗ no YouTube cookies found")
            return False

        # Write Netscape-format cookie file
        netscape = _to_netscape(cookies)
        _COOKIES_PATH.write_text(netscape)

        # Log what we got
        cookie_names = sorted(set(c["name"] for c in yt_cookies))
        print(f"[cookie_refresher] ✓ extracted {len(yt_cookies)} cookies: {', '.join(cookie_names[:10])}")
        print(f"[cookie_refresher] ✓ written to {_COOKIES_PATH} ({_COOKIES_PATH.stat().st_size:,} bytes)")
        return True

    except ImportError:
        print("[cookie_refresher] ✗ playwright not installed — run: pip install playwright && playwright install chromium")
        return False
    except Exception as e:
        print(f"[cookie_refresher] ✗ failed: {e}")
        return False
    finally:
        _LOCK.release()


def refresh_cookies_async(callback=None):
    """
    Non-blocking cookie refresh. Runs in a background thread.
    Optional callback receives a bool (success/failure).
    """
    def _run():
        result = refresh_cookies()
        if callback:
            callback(result)

    t = threading.Thread(target=_run, name="cookie-refresher", daemon=True)
    t.start()
    return t


def is_stale_cookie_error(error: str | Exception) -> bool:
    """
    Detect if a yt-dlp error is specifically about expired/invalid cookies.
    """
    msg = str(error).lower()
    return any(phrase in msg for phrase in (
        "cookies are no longer valid",
        "cookies have expired",
        "sign in to confirm",
        "sign in to confirm you",
        "this helps protect our community",
        "use --cookies-from-browser",
        "unable to extract initial player response",
    ))
